DROP TABLE IF EXISTS "aou_umpf_last";
DROP INDEX IF EXISTS "aou_umpf_posgrp_fact_flavour";
DROP TABLE IF EXISTS "aou_umpf_posgrp_fact";
DROP TABLE IF EXISTS "aou_umpf_posgrp";
DROP TABLE IF EXISTS "aou_umpf_dposition";
DROP TABLE IF EXISTS "aou_umpf_position";
DROP TABLE IF EXISTS "aou_umpf_security";
DROP TABLE IF EXISTS "aou_umpf_tag";
DROP TABLE IF EXISTS "aou_umpf_portfolio";
